name: Github Actions CI

on:
    push:
        branches: [main]
    pull_request:
        branches: ['main']

jobs:
    lint:
        name: Lint and CodeStyle
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - name: Lint code
              run: pnpm run lint:check
            - name: Check prettier
              run: pnpm run format:check

    typecheck:
        name: Typecheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - name: Check typecheck
              run: pnpm run build

    lint-old:
        name: (Legacy) Lint and CodeStyle
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - name: Lint code
              run: cd legacy-app && pnpm run lint
            - name: Check prettier
              run: cd legacy-app && pnpm run prettier:check

    typecheck-old:
        name: (Legacy) Typecheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - name: Check typecheck
              run: cd legacy-app && pnpm run typecheck
